baseURL = "http://mec-enigma.github.io/"
languageCode = "en-us"
title = "Enigma | The Computer Science Club @ MEC"
theme = "navigator-hugo"

enableRobotsTXT = true
googleAnalytics = ""

enableGitInfo = true
pygmentsCodeFences = true

defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    logo = "images/logo.png"

    ############# 2
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "Enigma | CS Club @ MEC"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "Enigma is the Official Computer Science Club at Mahindra Ecole Centrale"
    footerQuicklinkTitle = "ENGLISH Quicklinks"
    footerAboutTitle = "ENGLISH About"
    footerSubscribeTitle = "ENGLISH Subscribe"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "We are a group of college students, crazy passionate about Computer Science"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
        button  = true
        btnText = "Know More"
        btnURL  = "http://mec-enigma.github.io/about"
        videoThumb = "images/slider/video-player-thumb.jpg"
        # videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "We explore different topics during our sessions"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= "OUR STORY"
        title   = "The Enigma Blog"
        # subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        # subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "Mahindra Ecole Centrale, Survey No: 62/1A, Bahadurpally Jeedimetla, Hyderabad - 500043, Telangana, India"
        phone   = "040 - 67135100"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= "mailto:enigma@mechyd.ac.in"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "ENGLISH Let's Create Something Together"
        # subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "About"
        weight  = 2
    [[menu.nav]]
        name    = "Projects"
        url     = "Projects"
        weight  = 3
    [[menu.nav]]
        name    = "Blog"
        url     = "Blog"
        weight  = 4
    [[menu.nav]]
        name    = "Contact"
        url     = "Contact"
        weight  = 5

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "projects"
        url     = "projects"
        weight  = 2
    [[menu.quicklink]]
        name    = "blog"
        url     = "blog"
        weight  = 3